# teams-dev-samples
# Author: Hugo Bernier, updates by Bob German
#
# Each sample has an entry as show below
# 
# (ORIGINAL)
#    - name: microsoft-teams-apps-attendance
#      title: Attendance App Template
#      thumbnail: https://github.com/OfficeDev/microsoft-teams-apps-attendance/wiki/Images/Attendance_Readme_01.png
#      url: https://github.com/OfficeDev/microsoft-teams-apps-attendance
#      author: Microsoft
#      botframework: 4.6
#      type: app
#      language: powerapps, es6
#      summary: Attendance app is a Power Apps based solution to take attendance in educational tenant.
#      modifiedtext: May 14, 2020
#      modified: 2020-05-14
#
# (NEW)
#    - name: some-unique-name
#      title: 
#      type: apptemplate, barebones, demo, solution
#      features: bot, msgext, tab, taskmodule
#      summary: 
#      thumbnail: https://github.com/OfficeDev/microsoft-teams-apps-attendance/wiki/Images/Attendance_Readme_01.png
#      url: https://github.com/OfficeDev/microsoft-teams-apps-attendance
#      author: Microsoft
#      client_language: typescript, javascript, powerapps
#      client_platform: spa, spfx, powerapps
#      client_ui: react, angularjs, angular, knockout, jquery, vuejs
#      server_language: csharp, typescript, javascript, python, java, powerautomate
#      server_platform: netcore, express, restify, powerautomate
#      server_framework: bot3.x, bot4.x
#      modifiedtext: May 14, 2020
#      modified: 2020-05-14
#

site_name: Microsoft Teams Development Samples
plugins:
    - search
    - macros
    - markdownextradata
nav:
  - Samples:
    - By Type: index.md
    - By Client Language: samples/client_language.md
    - By Client Platform: samples/client_platform.md
    - By Client UI: samples/client_ui.md
    - By Server Framework: samples/server_framework.md
    - By Server Language: samples/server_language.md
    - By Server Platform: samples/server_platform.md
    - By Year: samples/year.md
    - By Author: samples/author.md
    - By Keyword: samples/keyword.md
    - All: samples/all.md
  - Getting Started:
    - Using the Samples: gettingstarted/index.md
  - Contributing:
    - Contribution Guide: contributing/index.md
theme:
  name: 'material'
  # custom_dir: 'theme/'
  palette:
    primary: 'pnp'
    accent: 'indigo'
  logo: 'img/pnp-samples-white.svg'
  feature:
    tabs: true
extra_css:
  - 'css/extra.css'
  - 'css/filter.css'
  - 'https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/10.0.0/css/fabric.min.css'
extra_javascript:
  - 'https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.4.1.min.js'
  - 'javascript/isotope.pkgd.min.js'
  - 'javascript/filtersamples.js'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
extra:
  version: '1.0.0-0'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/officedevpnp'
    - type: 'youtube'
      link: 'https://www.youtube.com/playlist?list=PLR9nK3mnD-OXgMjDBdjWUTRia89oixBhx'
    - type: 'link'
      link: 'https://aka.ms/sppnp'
  samples:

# Attendance app template
    - name: microsoft-teams-apps-attendance
      title: Attendance App Template
      type: apptemplate
      features: tab
      summary: Attendance app is a Power Apps based solution to take attendance in educational tenant.
      thumbnail: https://github.com/OfficeDev/microsoft-teams-apps-attendance/wiki/Images/Attendance_Readme_01.png
      url: https://github.com/OfficeDev/microsoft-teams-apps-attendance
      author: Microsoft
      client_language: powerapps, 
      client_platform: powerapps
      client_ui:
      server_language: powerautomate
      server_platform: powerautomate
      server_framework:
      modifiedtext: May 14, 2020
      modified: 2020-05-14

# HR Talent App
    - name: app-contoso-hr-talent-app
      title: HR Talent App demo/lab
      type: demo
      features: bot, msgext, tab, taskmodule
      summary: This is the lab for the 2019 Microsoft Teams Development Bootcamp. It shows all the extension points that were avaialble at the time. Includes two implementations, Bot Framework 3.x and Bot Framework 4.4 (Teams messages handled in code since they didn't get into the Bot Framework till 4.6)
      thumbnail: 
      url: https://github.com/OfficeDev/msteams-sample-contoso-hr-talent-app
      author: Microsoft
      client_language: typescript, javascript
      client_platform: spa, spfx
      client_ui: jquery
      server_language: csharp
      server_platform: netcore
      server_framework: bot3.x, bot4.x
      modifiedtext: October 4, 2019
      modified: 2019-10-04

# Teams Auth Bot (C#)
    - name: bot-teams-auth-csharp
      title: Teams Auth Bot (C#)
      type: barebones
      features: bot
      summary: Simple bot demonstrates how to log in a user so you can call APIs on their behalf
      thumbnail: 
      url: https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/46.teams-auth
      author: Microsoft
      client_language:
      client_platform:
      client_ui:
      server_language: csharp
      server_platform: netcore
      server_framework: bot4.x
      modifiedtext: July 9, 2020
      modified: 2020-07-09

# Teams Auth Bot (NodeJS)
    - name: bot-teams-auth-nodejs
      title: Teams Auth Bot (NodeJS)
      type: barebones
      features: bot
      summary: Simple bot demonstrates how to log in a user so you can call APIs on their behalf
      thumbnail: 
      url: https://github.com/microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/46.teams-auth
      author: Microsoft
      client_language:
      client_platform:
      client_ui:
      server_language: javascript
      server_platform: restify
      server_framework: bot4.x
      modifiedtext: July 9, 2020
      modified: 2020-07-09

# Consulting Bot
    - name: app-consulting-bot
      title: Consulting Bot
      type: demo
      features: bot, msgext, taskmodule
      summary: This app demonstrates two styles of Bot conversation - using natural language (best for 1:1 conversation) and using adaptive cards (best for Team channels and group chat)
      thumbnail: 
      url: https://github.com/pnp/teams-dev-samples/tree/master/samples/app-consulting-bot
      author: Bob German
      client_language:
      client_platform:
      client_ui:
      server_language: csharp
      server_platform: netcore
      server_framework: bot4.x
      modifiedtext: April 23, 2020
      modified: 2020-04-23

# Statebot
    - name: bot-statebot
      title: StateBot
      type: barebones
      features: bot
      summary: This simple bot demonstrates conversation state and user state in Bot Framework v4
      thumbnail: 
      url: 
      author: Bob German
      client_language:
      client_platform:
      client_ui:
      server_language: javascript
      server_platform: restify
      server_framework: bot4.x
      modifiedtext: August 12, 2019
      modified: 2019-08-12

# Field visit mashup
    - name: tab-spfx-field-visit
      title: Field visit mashup
      type: demo
      features: tab
      summary: A web part for use in Microsoft Teams that displays a mashup of information partaining to customer visits. 
      url: https://github.com/pnp/teams-dev-samples/tree/master/samples/tab-spfx-field-visit
      url: 
      author: Bob German
      client_language: typescript
      client_platform: spfx
      client_ui: react
      server_language:
      server_platform:
      server_framework:
      modifiedtext: April 20, 2019
      modified: 2019-04-20

  authors:
    - Bob German
    - Microsoft
repo_url: https://github.com/pnp/teams-dev-samples
edit_uri: tree/Docs/docs
site_url: https://pnp.github.io/teams-dev-samples/
site_favicon: favicon.ico

dev_addr: '192.168.24.50:8000'
# dev_addr: '127.0.0.1:443'
