blank_issues_enabled: false
contact_links:
  - name: General Teams development questions
    url: https://appsource.microsoft.com/en-us/product/office/WA200000739
    about: Issues and questions about Teams development in general
  - name: Bot Framework SDK
    url: https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-links-help?view=azure-bot-service-4.0
    about: Issues and questions about Bot development for Teams using the Bot Framework SDK
  - name: Microsoft Graph
    url: https://developer.microsoft.com/en-us/graph/support
    about: Issues and questions about the Microsoft Graph
  - name: Microsoft Teams JavaScript SDK
    url: https://docs.microsoft.com/en-us/javascript/api/overview/msteams-client?view=msteams-client-js-latest
    about: Use the feedback link at the footer of the docs page
  - name: SharePoint Framework with Teams
    url: https://github.com/SharePoint/sp-dev-docs/issues 
    about: Use the SP Dev Docs repository issues list
  - name: Microsoft Tech Community
    url: https://techcommunity.microsoft.com/t5/microsoft-teams/ct-p/MicrosoftTeams
    about: Conversations and articles about Microsoft Teams
